"""
Property-based tests for the Classification Service.

Feature: tattva-exam-engine

Two properties under test:
  Property 7 — classification output always conforms to schema
  Property 8 — low-confidence note is present and ≤ 200 chars

All @settings use max_examples=20, deadline=None, and
suppress_health_check=[HealthCheck.too_slow] as specified.

All tests mock google.generativeai — no real API calls are made.

Validates: Requirements 4.1 (schema), 4.5 (low-confidence note constraint)
"""

from __future__ import annotations

import json
import uuid
from typing import Optional

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from app.services.classification.service import (
    ClassificationResult,
    _build_classification_result,
    validate_classification_output,
)


# ---------------------------------------------------------------------------
# Strategy helpers
# ---------------------------------------------------------------------------

# Non-empty text up to 255 chars (subject / topic names)
_nonempty_text = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N", "Z", "P")),
    min_size=1,
    max_size=100,
).filter(lambda s: s.strip())  # ensure at least one non-whitespace char

# Module numbers: positive integers 1..99
_module_number = st.integers(min_value=1, max_value=99)

# Confidence values
_confidence = st.sampled_from(["high", "medium", "low"])

# Valid note texts for low confidence (1..200 non-empty chars)
_note_text = st.text(
    alphabet=st.characters(whitelist_categories=("L", "N", "Z", "P")),
    min_size=1,
    max_size=200,
).filter(lambda s: s.strip())


@st.composite
def valid_classification_dict(draw) -> dict:
    """
    Strategy that generates valid classification output dicts covering all three
    confidence levels.  When confidence=='low', a note is always included.
    """
    confidence: str = draw(_confidence)
    subject: str = draw(_nonempty_text)
    module_number: int = draw(_module_number)
    topic: str = draw(_nonempty_text)
    is_new_topic: bool = draw(st.booleans())

    d: dict = {
        "subject": subject,
        "module_number": module_number,
        "topic": topic,
        "is_new_topic": is_new_topic,
        "confidence": confidence,
    }

    if confidence == "low":
        note = draw(_note_text)
        d["note"] = note
    elif draw(st.booleans()):
        # Optionally include a note for high/medium (still valid)
        note = draw(_note_text)
        d["note"] = note

    return d


@st.composite
def low_confidence_classification_dict(draw) -> dict:
    """
    Strategy that always generates a low-confidence classification dict with
    a note field.
    """
    subject: str = draw(_nonempty_text)
    module_number: int = draw(_module_number)
    topic: str = draw(_nonempty_text)
    is_new_topic: bool = draw(st.booleans())
    note: str = draw(_note_text)

    return {
        "subject": subject,
        "module_number": module_number,
        "topic": topic,
        "is_new_topic": is_new_topic,
        "confidence": "low",
        "note": note,
    }


# ---------------------------------------------------------------------------
# Property 7 — classification output always conforms to schema
#
# For any dict generated by `valid_classification_dict`:
#   - validate_classification_output returns True
#   - _build_classification_result produces a ClassificationResult with the
#     same field values as the input dict
#   - confidence is always one of {"high", "medium", "low"}
#   - subject and topic are non-empty strings
#   - module_number is a positive integer
# ---------------------------------------------------------------------------

@settings(max_examples=20, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(output=valid_classification_dict())
def test_property7_classification_output_conforms_to_schema(output: dict) -> None:
    """
    Feature: tattva-exam-engine, Property 7: classification output conforms to schema

    For any valid classification dict, validate_classification_output returns True
    and the resulting ClassificationResult has the correct field values.

    Validates: Requirements 4.1, 4.6
    """
    # --- Schema validation must pass ---
    assert validate_classification_output(output) is True, (
        f"validate_classification_output returned False for seemingly valid output:\n{output!r}"
    )

    # --- Build result and verify field types / values ---
    result: ClassificationResult = _build_classification_result(output)

    # subject: non-empty string
    assert isinstance(result.subject, str), "subject must be a string"
    assert result.subject.strip(), "subject must be non-empty after strip"

    # module_number: positive integer
    assert isinstance(result.module_number, int), "module_number must be an int"
    assert result.module_number >= 1, "module_number must be a positive integer"

    # topic: non-empty string
    assert isinstance(result.topic, str), "topic must be a string"
    assert result.topic.strip(), "topic must be non-empty after strip"

    # is_new_topic: bool
    assert isinstance(result.is_new_topic, bool), "is_new_topic must be a bool"

    # confidence: one of the three allowed values
    assert result.confidence in ("high", "medium", "low"), (
        f"confidence must be 'high'|'medium'|'low', got {result.confidence!r}"
    )

    # note: None or string ≤ 200 chars
    if result.note is not None:
        assert isinstance(result.note, str), "note must be a string when present"
        assert len(result.note) <= 200, (
            f"note exceeds 200 chars: {len(result.note)}"
        )

    # Round-trip: values match the input dict (after strip)
    assert result.subject == output["subject"].strip(), (
        f"subject mismatch: {result.subject!r} vs {output['subject']!r}"
    )
    assert result.module_number == int(output["module_number"]), (
        f"module_number mismatch: {result.module_number} vs {output['module_number']}"
    )
    assert result.topic == output["topic"].strip(), (
        f"topic mismatch: {result.topic!r} vs {output['topic']!r}"
    )
    assert result.confidence == output["confidence"], (
        f"confidence mismatch: {result.confidence!r} vs {output['confidence']!r}"
    )


# ---------------------------------------------------------------------------
# Property 8 — low-confidence note is present and ≤ 200 chars
#
# For any low-confidence classification dict:
#   - validate_classification_output returns True
#   - result.note is present (not None), non-empty after strip, and ≤ 200 chars
#   - result.confidence == "low"
# ---------------------------------------------------------------------------

@settings(max_examples=20, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(output=low_confidence_classification_dict())
def test_property8_low_confidence_note_present_and_within_limit(output: dict) -> None:
    """
    Feature: tattva-exam-engine, Property 8: low-confidence note ≤ 200 chars

    For any low-confidence output, validate_classification_output accepts it,
    and the resulting ClassificationResult has a non-empty note of ≤ 200 chars.

    Validates: Requirements 4.5
    """
    # Precondition: output["note"] must be non-empty and ≤ 200 chars
    # (the strategy guarantees this; we verify the invariant holds all the way through)
    assert output["confidence"] == "low"
    assert "note" in output, "Strategy must include note for low confidence"
    assert output["note"].strip(), "Strategy must include a non-empty note"
    assert len(output["note"]) <= 200, "Strategy note must be ≤ 200 chars"

    # --- Schema validation must accept this output ---
    assert validate_classification_output(output) is True, (
        f"validate_classification_output rejected valid low-confidence output:\n{output!r}"
    )

    # --- Build result ---
    result: ClassificationResult = _build_classification_result(output)

    # confidence is 'low'
    assert result.confidence == "low", (
        f"Expected confidence='low', got {result.confidence!r}"
    )

    # note must be present
    assert result.note is not None, (
        "note must not be None for low-confidence classification"
    )

    # note must be non-empty
    assert result.note.strip(), (
        "note must be non-empty (non-whitespace) for low-confidence classification"
    )

    # note must be ≤ 200 chars
    assert len(result.note) <= 200, (
        f"note exceeds 200 chars for low-confidence: {len(result.note)} chars"
    )


# ---------------------------------------------------------------------------
# Supplementary: validate_classification_output rejects invalid dicts
# ---------------------------------------------------------------------------

@st.composite
def _invalid_confidence_dict(draw) -> dict:
    """Strategy producing otherwise-valid dicts but with an invalid confidence value."""
    d = draw(valid_classification_dict())
    # Replace confidence with something invalid
    bad_confidence = draw(
        st.text(min_size=1, max_size=20).filter(
            lambda s: s not in ("high", "medium", "low")
        )
    )
    d["confidence"] = bad_confidence
    return d


@settings(max_examples=20, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(output=_invalid_confidence_dict())
def test_property7_invalid_confidence_always_rejected(output: dict) -> None:
    """
    Feature: tattva-exam-engine, Property 7 (negative): invalid confidence rejected

    Any dict with a confidence value outside {'high', 'medium', 'low'} must
    be rejected by validate_classification_output.

    Validates: Requirements 4.1, 4.6
    """
    assert validate_classification_output(output) is False, (
        f"Expected False for invalid confidence {output['confidence']!r}, got True"
    )


@st.composite
def _note_too_long_dict(draw) -> dict:
    """Strategy producing a dict with a note exceeding 200 chars."""
    d = draw(low_confidence_classification_dict())
    # Override note with one that's too long
    d["note"] = draw(
        st.text(min_size=201, max_size=300)
    )
    return d


@settings(max_examples=20, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(output=_note_too_long_dict())
def test_property8_note_over_200_chars_always_rejected(output: dict) -> None:
    """
    Feature: tattva-exam-engine, Property 8 (negative): note > 200 chars rejected

    Any classification dict with a note exceeding 200 characters must be rejected
    by validate_classification_output.

    Validates: Requirements 4.5
    """
    assert len(output["note"]) > 200, "Strategy must provide note > 200 chars"
    assert validate_classification_output(output) is False, (
        f"Expected False for note of length {len(output['note'])}, got True"
    )
